stages:
    - mavenbuild
    - maventest
    - autoDeploy
    - androidbuild
    - androidtest
    
autoDeploy:
    stage: autodeploy
    tags:
        - shell
    script:
        - cd Spring
        - mvn package
        - sudo mv target/*.jar /target/web-demo.jar
        - sudo systemctl stop web-demo
        - sudo systemctl start web-demo

maven-build: 
    stage: mavenbuild
    tags: 
        - BACKEND 
    script: 
        - cd Spring 
        - mvnpackage –B
        
maven-test: 
    stage: maventest
    tags: 
        - BACKEND
    script: 
        - cd Spring 
        - mvntest 
    artifacts: 
        paths: 
            - Spring/target/*.jar
            
android-build:
    image: javiersantos/android-ci:latest    
    stage: androidbuild    
    before_script:        
        - export GRADLE_USER_HOME='pwd'/.gradle        
        - chmod +x ./Frontend/hiveFrontend/gradlew    
    tags:        
        - FRONTEND    
    script:        
        - cd Frontend/hiveFrontend/        
        - ./gradlew assemble    
    artifacts:        
        paths:            
            - Frontend/hiveFrontend/app/build/outputs/

unitTests:    
    image: javiersantos/android-ci:latest    
    stage: androidtest    
    before_script:        
        - export GRADLE_USER_HOME='pwd'/.gradle
        - chmod +x ./Frontend/hiveFrontend/gradlew    
    tags:        
        - FRONTEND    
    script:        
        - cd Frontend/hiveFrontend/        
        - ./gradlew assemble